### PR TITLE
Remove uuid dependency

### PR DESCRIPTION
**Pull request by frodeaa**
Use crypto#randomUUID to generate uuidv4 where needed

Rel: https://nodejs.org/docs/latest-v20.x/api/crypto.html#cryptorandomuuidoptions
Rel: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID

### CODE REVIEW

**Review by wholien — APPROVED** [review]

**Comment by Svapnil** [comment]
Thanks for this @frodeaa, this looks good to me

**Comment by Svapnil** [comment]
@frodeaa will leave it up to you to merge, otherwise I will in 24 hours. Thanks for being the first contribution to the repository

**Comment by Svapnil** [comment]
This decision to rely on `randomUUID` in Node.js comes with some tradeoffs 

Namely, I'm working to get this package onto the frontend (using webpack). The problem is that webpack's crypto polyfill doesn't even implement randomUUID. Will update when I find out how to resolve

**Comment by frodeaa** [comment]
> This decision to rely on `randomUUID` in Node.js comes with some tradeoffs
> 
> Namely, I'm working to get this package onto the frontend (using webpack). The problem is that webpack's crypto polyfill doesn't even implement randomUUID. Will update when I find out how to resolve

Do you need polyfill? The browsers seems to support randomUUID
https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID#browser_compatibility

**Pull request merged**
